export const SET_SEARCHED_ADS='SET_SEARCHED_ADS ';
export const ADD_AD='ADD_AD';
export const SET_LOADING_ADS='SET_LOADINGS_ADS';
export const SET_SEARCHING='SET_SEARCHING';
export const SET_CATEGORIES='SET_CATEGORIES';
export const SEARCH_CAT='SEARCH_CAT';
export const SET_SUBCATEGORIES='SET_SUBCATEGORIES';
export const SEARCH_SUB='SEARCH_SUB';
export const SEARCH_LOCATION='SEARCH_LOCATION';
export const SEARCH_STRING='SEARCH_STRING';
export const SET_LOADING_CATEGORIES='SET_LOADING_CATEGORIES';
export const SET_LOADING_SUBCATEGORIES='SET_LOADING_SUBCATEGORIES';


